FROM nvidia/cuda:10.0-devel-ubuntu18.04


# update apt
RUN apt-get update

# install general dependencies
RUN apt-get install -y python3-pip wget git autoconf libtool nvidia-modprobe \
    software-properties-common cmake openssh-server openssh-client numactl


# setup cluster user and SSH access to container
ENV USER cluster
RUN useradd -ms /bin/bash $USER && usermod -p '*' $USER
ENV HOME /home/$USER
ENV SSHDIR $HOME/.ssh
RUN mkdir -p ${SSHDIR} \
    && touch ${SSHDIR}/sshd_config \
    && ssh-keygen -t rsa -f ${SSHDIR}/ssh_host_rsa_key -N '' \
    && cp ${SSHDIR}/ssh_host_rsa_key.pub ${SSHDIR}/authorized_keys \
    && cp ${SSHDIR}/ssh_host_rsa_key ${SSHDIR}/id_rsa \
    && echo "    IdentityFile ${SSHDIR}/id_rsa" >> ${SSHDIR}/config \
    && echo "    StrictHostKeyChecking no" >> ${SSHDIR}/config \
    && echo "    UserKnownHostsFile /dev/null" >> ${SSHDIR}/config \
    && echo "    Port 2022" >> ${SSHDIR}/config \
    && echo 'Port 2022' >> ${SSHDIR}/sshd_config \
    && echo "HostKey ${SSHDIR}/ssh_host_rsa_key" >> ${SSHDIR}/sshd_config \
    && echo "PidFile ${SSHDIR}/sshd.pid" >> ${SSHDIR}/sshd_config \
    && echo "PasswordAuthentication no" >> ${SSHDIR}/sshd_config \
    && chmod -R 600 ${SSHDIR}/* \
    && chown -R ${USER}:${USER} ${SSHDIR}/


WORKDIR /home/$USER/

# Examples
WORKDIR /home/$USER/byteps/bytescheduler/examples/pytorch/

# Set default shell to /bin/bash
SHELL ["/bin/bash", "-cu"]

EXPOSE 2022

COPY container_entrypoint.sh /etc/

RUN chmod +x /etc/container_entrypoint.sh
ENTRYPOINT /etc/container_entrypoint.sh