set -x
export DMLC_NUM_WORKER=2
export DMLC_NUM_SERVER=2
export DMLC_PS_ROOT_URI=127.0.0.1
export DMLC_PS_ROOT_PORT=12720

export DMLC_ENABLE_RDMA=1
export BYTEPS_P2P_ON=1

export BYTEPS_LOCAL_SIZE=1
export BYTEPS_FORCE_DISTRIBUTED=1
export ENABLE_GLOBAL_RANK=1
export BYTEPS_PARTITION_BYTES=4096000
export BYTEPS_OMP_THREAD_PER_GPU=8